{% set name = "falcon-apispec" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3be2d7a544852fb6ec78bcdd27f28cb62418337ab85ab23685632f7946f667e5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - apispec >=1.0
    - falcon
    - pyyaml >=3.10

test:
  requires:
    - python {{ python_min }}
  imports:
    - falcon_apispec

about:
  home: https://github.com/alysivji/falcon-apispec
  license: MIT
  license_family: MIT
  # Manually packaged license: https://github.com/alysivji/falcon-apispec/pull/15
  license_file: LICENSE
  summary: apispec plugin that generates OpenAPI specification (aka Swagger) for Falcon web applications

  dev_url: https://github.com/alysivji/falcon-apispec

extra:
  recipe-maintainers:
    - synapticarbors
